version: '2'

services:
  reverse_proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hdfs

  namenode:
    build: ./namenode
    ports:
      - 9871:9871
      - 9870:9870 # web ui
      - 8020:8020

    networks:
      - hdfs
    labels:
      - "traefik.frontend.rule=Host:namenode.docker.localhost"
    depends_on:
      - reverse_proxy
    
  datanode:
    build: ./datanode
    ports:
      - 9867:9867
      - 9866:9866
      - 9865:9865
      - 9864:9864 # web ui
    depends_on: 
      - namenode
    networks:
      - hdfs
    labels:
      - "traefik.frontend.rule=Host:datanode1.docker.localhost"

  ping:
    image: alpine
    command: ping namenode.docker.localhost
    networks:
      - hdfs
    labels:
      - "traefik.frontend.rule=Host:pinger.docker.localhost"
    depends_on:
      - reverse_proxy

networks:
  hdfs:

## from older versions
# Namenode ports: 50470 --> 9871, 50070 --> 9870, 8020 --> 9820
# Secondary NN ports: 50091 --> 9869, 50090 --> 9868
# Datanode ports: 50020 --> 9867, 50010 --> 9866, 50475 --> 9865, 50075 --> 9864