version: '2'
services:
  namenode:
    image: hadoop-3:latest
    networks:
      - hadoop
    ports:
      - 9870:9870  # hdfs namenode ui
    command: namenode

  datanode:
    image: hadoop-3:latest
    depends_on: 
      - namenode
    networks:
      - hadoop
    ports:
      - 9864:9864  # hdfs datanode ui
    command: datanode


  spark:
    image: hadoop-3:latest
    container_name: spark
    depends_on: 
      - datanode
      - namenode
    ports:
      - 8088:8088 # yarn resourcemanager ui
      - 8081:8081 # spark worker ui
      - 8080:8080 # spark master ui
    networks:
      - hadoop
    command: resourcemanager

  nodemanager:
    image: hadoop-3:latest
    depends_on: 
      - spark
    networks:
      - hadoop
    ports:
      - 8042:8042 # yarn nodemanager ui
    command: nodemanager

    # volumes:
      # - node_manager_tmp:/tmp/
      # - /tmp/:${LOCAL_DIR}/compose/yarn/node_manager/tmp/
networks:
  hadoop:

volumes:
  node_manager_tmp:
