version: '2'

services:
  namenode:
    build: ./hdfs/namenode
    networks:
      - hdfs
    ports:
      - 9870:9870

  datanode:
    build: ./hdfs/datanode
    depends_on: 
      - namenode
    networks:
      - hdfs
    ports:
      - 9864:9864



  # yarn_resource_manager:
  #   build: ./yarn/resource_manager
  #   container_name: resourcemanager
  #   depends_on: 
  #     - namenode
  #   ports:
  #     - 8088:8088
  #   networks:
  #     - hdfs

  spark:
    build: ./yarn/spark
    container_name: spark
    depends_on: 
      - namenode
    ports:
      - 8088:8088
    networks:
      - hdfs


  yarn_node_manager:
    build: ./yarn/node_manager
    depends_on: 
      - namenode
    networks:
      - hdfs

networks:
  hdfs: