version: '2'

services:
  namenode:
    build: ./namenode
    network_mode: host
# http://localhost:9870

  datanode:
    build: ./datanode
    depends_on: 
      - namenode
    network_mode: host
# http://localhost:9864

#   yarn:
#     build: ./yarn
#     depends_on: 
#       - namenode
#     network_mode: host
# # http://localhost:8088
# # http://localhost:19888 job history

  spark:
    build: ./spark
    depends_on: 
      - namenode
    network_mode: host

networks:
  hdfs:


## from older versions
# Namenode ports: 50470 --> 9871, 50070 --> 9870, 8020 --> 9820
# Secondary NN ports: 50091 --> 9869, 50090 --> 9868
# Datanode ports: 50020 --> 9867, 50010 --> 9866, 50475 --> 9865, 50075 --> 9864